const fs = require('fs');
let html = fs.readFileSync('index.html', 'utf8');

const firstViewStart = '<section id="view-usuarios" class="view-section">';
const firstViewIdx = html.indexOf(firstViewStart);

const secondViewStart = '<section id="view-usuarios" class="view-section" style="display:none;">';
const secondViewIdx = html.indexOf(secondViewStart);

if (firstViewIdx === -1 || secondViewIdx === -1) {
    console.error("Could not find both views!");
    process.exit(1);
}

// Find the end of the first view
const firstViewEndToken = '</section>';
const firstViewEndIdx = html.indexOf(firstViewEndToken, firstViewIdx) + firstViewEndToken.length;

let firstViewHTML = html.substring(firstViewIdx, firstViewEndIdx);

// Extract modal from second view
const modalStartToken = '<div id="modal-credenciales-usuario"';
const modalStartIdx = html.indexOf(modalStartToken, secondViewIdx);
const modalEndIdx = html.indexOf('</div>\r\n                </div>', modalStartIdx) + '</div>\r\n                </div>'.length;
let modalHTML = '';
if (modalStartIdx !== -1) {
    // A bit hacky to find the end of the modal, let's just grab it until the end of the section
    const secEndIdx = html.indexOf('</section>', secondViewIdx);
    modalHTML = html.substring(modalStartIdx, secEndIdx);
}

// Transform the first view
// 1. Wrap with dashboard-container
firstViewHTML = firstViewHTML.replace('<section id="view-usuarios" class="view-section">', '<section id="view-usuarios" class="view-section">\r\n                <div class="dashboard-container">');
firstViewHTML = firstViewHTML.replace('</section>', '</div>\r\n' + modalHTML + '</section>');

// 2. Change IDs
firstViewHTML = firstViewHTML.replace('id="usuario-username" placeholder="arossi.med"', 'id="input-nuevo-usuario-email" placeholder="ejemplo"');
firstViewHTML = firstViewHTML.replace('id="usuario-rol"', 'id="select-nuevo-usuario-rol"');
firstViewHTML = firstViewHTML.replace('<button type="submit" class="btn btn-primary"', '<button id="btn-guardar-usuario" type="submit" class="btn btn-primary"');
firstViewHTML = firstViewHTML.replace('id="users-table-body"', 'id="tabla-usuarios-body"');

// We also need to remove the "Contraseña" block since the password is autogenerated.
// Looking for:
// <div class="form-group">
//     <label class="form-label" for="usuario-password">Contraseña</label>
//     <input type="password" class="form-control" name="password" id="usuario-password"
//         placeholder="********" required>
// </div>
firstViewHTML = firstViewHTML.replace(/<div class="form-group">\s*<label class="form-label" for="usuario-password">Contraseña<\/label>\s*<input type="password" class="form-control" name="password" id="usuario-password"\s*placeholder="\*\*\*\*\*\*\*\*" required>\s*<\/div>/g, '');

// Also remove `data-target="#modal-usuarios" data-modal="true"` from the submit button since we handle it in JS now.
firstViewHTML = firstViewHTML.replace('data-target="#modal-usuarios" data-modal="true"', '');

// Now we need to remove the second view entirely.
const secondViewEndIdx = html.indexOf('</section>', secondViewIdx) + '</section>'.length;
// Wait, the second view has `</section>` at the end of it. Let's make sure it's the right one.
// Let's just do a string replacement.
let newHtml = html.substring(0, firstViewIdx) + firstViewHTML + html.substring(firstViewEndIdx, secondViewIdx) + html.substring(secondViewEndIdx);

fs.writeFileSync('index.html', newHtml);
console.log("Success!");
